[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.10"
tokio = { version = "1.20.1", features = ["full"] }
futures-util = "0.3.23"
bollard = "0.13"
